In [ ]:
import pandas as pd

def get_list(column_name):
    # Path to the CSV file
    csv_path = './retail_sales_dataset.csv'

    try:
      # Read the CSV file into a DataFrame
      df = pd.read_csv(csv_path)

      # Check if the specified column exists in the DataFrame
      if column_name in df.columns:
        # Return the column data as a list
        return df[column_name].tolist()
      else:
        # If the column does not exist, raise an error
        raise ValueError("Column name not found in the DataFrame")
    except Exception as e:
      # Print any error that occurs during the process
      print(f"An error occurred: {e}")

In [ ]:
Transaction_ID = get_list("Transaction ID")
date = get_list("Date")
Customer_ID = get_list("Customer ID")
Gender = get_list("Gender")
Age = get_list("Age")
Product_Category = get_list("Product Category")
Quantity = get_list("Quantity")
prices_per_unit = get_list("Price per Unit")
Total_Amount = get_list("Total Amount")

In [ ]:
sales_df= pd.read_csv('/content/retail_sales_dataset.csv')

In [ ]:
sales_df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [ ]:
# Get the data types of each feature in the sales_df DataFrame. Store it in the dtypes variable.
feature_types = sales_df.dtypes

In [ ]:
print(feature_types)

Transaction ID       int64
Date                object
Customer ID         object
Gender              object
Age                  int64
Product Category    object
Quantity             int64
Price per Unit       int64
Total Amount         int64
dtype: object

In [ ]:
# Sort the dataset by decreasing amount
sorted_df = sales_df.sort_values('Total Amount', ascending=False)
top_10 = sorted_df.head(10)

In [ ]:
# Display the results
top_10

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
945,946,2023-05-08,CUST946,Male,62,Electronics,4,500,2000
71,72,2023-05-23,CUST072,Female,20,Electronics,4,500,2000
14,15,2023-01-16,CUST015,Female,42,Electronics,4,500,2000
576,577,2023-02-13,CUST577,Male,21,Beauty,4,500,2000
571,572,2023-04-20,CUST572,Male,31,Clothing,4,500,2000
268,269,2023-02-01,CUST269,Male,25,Clothing,4,500,2000
502,503,2023-10-25,CUST503,Male,45,Beauty,4,500,2000
926,927,2023-06-24,CUST927,Male,43,Electronics,4,500,2000
252,253,2023-08-31,CUST253,Female,53,Clothing,4,500,2000
546,547,2023-03-07,CUST547,Male,63,Clothing,4,500,2000

In [ ]:
# Find out which product name appears most frequently
product_counts = sales_df.value_counts('Product Category')
product_counts.head()

Product Category
Clothing       351
Electronics    342
Beauty         307
Name: count, dtype: int64

In [ ]:
# Units sold per product name
grouped_by_product_category = sales_df.groupby('Product Category')
quantity_sold = grouped_by_product_category['Quantity'].sum()

In [ ]:
quantity_sold.sort_values(ascending=False).head()

Product Category
Clothing       894
Electronics    849
Beauty         771
Name: Quantity, dtype: int64

In [ ]:
# Filter by product name and units sold
df_filtered = sales_df[(sales_df['Product Category'] == 'Electronics') & (sales_df['Quantity'] > 1)]

In [ ]:
df_filtered.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600
12,13,2023-08-05,CUST013,Male,22,Electronics,3,500,1500
14,15,2023-01-16,CUST015,Female,42,Electronics,4,500,2000
17,18,2023-04-30,CUST018,Female,47,Electronics,2,25,50

In [ ]:
# Specify one transaction ID from the results above
index = 15

# Filter by the transaction ID
row = sales_df[(sales_df["Transaction ID"]==index)]

# Print the products found in the transaction ID
row['Product Category']

14    Electronics
Name: Product Category, dtype: object

In [ ]:
# Find the total amount per invoice
# create a pivot table using "Transaction ID" as index.
# use the columns "Quantity" and "Total Amount" as values, aggregating by sum
pivot_by_transaction = sales_df.pivot_table(index="Transaction ID", values=("Quantity","Total Amount"), aggfunc="sum")

In [ ]:
pivot_by_transaction.head()

                Quantity  Total Amount
Transaction ID
1                      3           150
2                      2          1000
3                      1            30
4                      1           500
5                      2           100

In [ ]:
# Get the datatype of the pivot table output
type(pivot_by_transaction)

pandas.core.frame.DataFrame

In [ ]:
pivot_by_transaction.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 1 to 1000
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Quantity      1000 non-null   int64
 1   Total Amount  1000 non-null   int64
dtypes: int64(2)
memory usage: 23.4 KB

In [ ]:
# Slice the pivot_by_transaction DataFrame from the 21th transaction to the 60th
pbt_sliced = pivot_by_transaction.iloc[20:60]

In [ ]:
print("number of rows:", len(pbt_sliced))

number of rows: 40

In [ ]:
# Print start and end rows
print(pbt_sliced.iloc[0])
print(pbt_sliced.iloc[39])

Quantity          1
Total Amount    500
Name: 21, dtype: int64
Quantity          3
Total Amount    150
Name: 60, dtype: int64

In [ ]:
# Analyzing the amount per transaction
# find the sum, mean, max in pbt_sliced

amount_sum = pbt_sliced.sum()
amount_mean = pbt_sliced.mean()
amount_max = pbt_sliced.max()

# find the correlation of the numerical variables of pbt_sliced
corr_units_amount = pbt_sliced[['Quantity', 'Total Amount']].corr()

In [ ]:
# Print the results

print("The sum of all sales is:", round(amount_sum, 2))
print("The mean amount per purchase is:", round(amount_mean, 2))
print("The highest purchase amount is:", round(amount_max, 2))
print("The correlation between the amount and number of units sold per transaction is",
      round(corr_units_amount.loc['Total Amount']['Quantity'],4))

The sum of all sales is: Quantity           96
Total Amount    17740
dtype: int64
The mean amount per purchase is: Quantity          2.4
Total Amount    443.5
dtype: float64
The highest purchase amount is: Quantity           4
Total Amount    1500
dtype: int64
The correlation between the amount and number of units sold per transaction is 0.3949